version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - python3 -m venv .venv
      - source .venv/bin/activate~
      - pip install --upgrade pip

  pre_build:
    commands:
      - echo Running pre-build steps...
      - source .venv/bin/activate
  build:
    commands:
      - echo Running build steps...
      - source .venv/bin/activate
      - echo Packaging application...

  post_build:
    commands:
      - echo Build completed successfully.
      - ls -la
artifacts:
  files:
    - "**/*"
